<body>
    <div class="d-flex">
        <?php
            require_once('../Components/Header/index.php');
        ?>
        <main class="container">
            <table class="tabela-relatorio">
                <thead>
                    <tr>
                        <td>
                            <strong>N</strong>
                        </td>
                        <td>
                            <strong>ESSENCIA</strong>
                        </td>
                        <td>
                            <strong>MESA</strong>
                        </td>
                        <td>
                            <strong>NARGUILE</strong>
                        </td>
                        <td>
                            <strong>OPEN</strong>
                        </td>
                        <td>
                            <strong>acao</strong>
                        </td>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            <p>1</p>
                        </td>
                        <td>
                            <p>7belo</p>
                        </td>
                        <td>
                            <p>36</p>
                        </td>
                        <td>
                            <p>nao</p>
                        </td>
                        <td>
                            <p>sim</p>
                        </td>
                        <td>
                            <a
                                href="#"
                            >
                                <img 
                                    src="../assets/img/editar.png"
                                    alt="icone-editar"
                                    class="icone-relatorio"
                                >
                            </a>
                            <a
                                href="#"
                            >
                                <img 
                                    src="../assets/img/lixeira.png"
                                    alt="icone-excluir"
                                    class="icone-relatorio"
                                >
                            </a>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p>2</p>
                        </td>
                        <td>
                            <p>Lemon Fresh</p>
                        </td>
                        <td>
                            <p>14</p>
                        </td>
                        <td>
                            <p>sim</p>
                        </td>
                        <td>
                            <p>nao</p>
                        </td>
                        <td class="tabela-relatorio-botoes">
                            <a
                                href="#"
                            >
                                <img 
                                    src="../assets/img/editar.png"
                                    alt="icone-editar"
                                    class="icone-relatorio"
                                >
                            </a>
                            <a
                                href="#"
                            >
                                <img 
                                    src="../assets/img/lixeira.png"
                                    alt="icone-excluir"
                                    class="icone-relatorio"
                                >
                            </a>
                        </td>
                    </tr>
                </tbody>
                <tfoot>
                    <tr>
                        <td>
                            <p>3</p>
                        </td>
                        <td>
                            <p>7belo</p>
                        </td>
                        <td>
                            <p>41</p>
                        </td>
                        <td>
                            <p>nao</p>
                        </td>
                        <td>
                            <p>nao</p>
                        </td>
                        <td class="tabela-relatorio-botoes">
                            <a
                                href="#"
                            >
                                <img 
                                    src="../assets/img/editar.png"
                                    alt="icone-editar"
                                    class="icone-relatorio"
                                >
                            </a>
                            <a
                                href="#"
                            >
                                <img 
                                    src="../assets/img/lixeira.png"
                                    alt="icone-excluir"
                                    class="icone-relatorio"
                                >
                            </a>
                        </td>
                    </tr>
                </tfoot>
            </table>
        </main>
        <?php
            require_once('../Components/Footer/index.php');
        ?>
    </div>
</body>
